source(here::here("R", "utilities.R"))

# Setup the Republican candidates' information =================================
cand_rep_2020 <- list(
  tibble(
    first_name = "Donald",
    last_name = "Trump",
    campaign_name = "Donald J. Trump for President",
    campaign_website = "https://www.donaldjtrump.com/",
    actblue_link = NA,
    other_link = c(
      "https://secure.winred.com/djt/finance-team-daily-goal",
      "https://secure.winred.com/djt/defend-the-election",
      "https://secure.winred.com/tmagac/election-defense-task-force",
      "https://secure.donaldjtrump.com/donate",
      "https://secure.winred.com/djt/2020-standing-with-president-trump/",
      "https://secure.winred.com/djt/we-made-history",
      "https://secure.winred.com/tmagac/contribute",
      "https://secure.winred.com/djt/jan-2020-eom",
      "https://secure.winred.com/djt/2020-sotu/",
      "https://secure.winred.com/djt/2020-pb-dinner-sweepstakes",
      "https://secure.donaldjtrump.com/teamtrump-alerts",
      "https://secure.winred.com/tmagac/impeachment-defense-force",
      "https://secure.winred.com/tmagac/impeachment-defense-force-il17",
      "https://secure.donaldjtrump.com/january-2019-eom-4xmatch",
      "https://secure.donaldjtrump.com/donate/",
      "https://secure.donaldjtrump.com/we-made-history"
    ),
    FEC_ID_cmte = "C00580100",
    FEC_ID_cand = "P80001571"
  ),
  tibble(
    first_name = "Bill",
    last_name = "Weld",
    campaign_name = "Weld 2020",
    campaign_website = "http://www.weld2020.org/",
    actblue_link = NA,
    other_link = c(
      "https://secure.anedot.com/blackhorseflag/donate",
      "https://secure.anedot.com/blackhorseflag/china-ukraine",
      "https://secure.anedot.com/blackhorseflag/fa_oct19",
      "https://secure.anedot.com/blackhorseflag/sept19",
      "https://secure.anedot.com/blackhorseflag/oct19",
      "https://secure.anedot.com/blackhorseflag/nov19",
      "https://secure.anedot.com/blackhorseflag/dec19",
      "https://secure.anedot.com/blackhorseflag/bafd",
      "https://secure.anedot.com/blackhorseflag/jan20",
      "https://secure.anedot.com/blackhorseflag/feb20",
      "https://secure.anedot.com/blackhorseflag/march20",
      "https://secure.anedot.com/blackhorseflag/nhvff",
      "https://secure.anedot.com/blackhorseflag/stvf",
      "https://secure.anedot.com/blackhorseflag/nhaf",
      "https://secure.anedot.com/blackhorseflag/ngaf"
    ),
    FEC_ID_cmte = "C00700906",
    FEC_ID_cand = "P00011239"
  ),
  tibble(
    first_name = "Joe",
    last_name = "Walsh",
    campaign_name = "Walsh 2020",
    campaign_website = "https://www.joewalsh.org/",
    actblue_link = NA,
    other_link = c(
      "https://secure.anedot.com/walsh-for-president/donate-w",
      "https://secure.anedot.com/walsh-for-president/donate",
      paste0(
        "https://secure.anedot.com/walsh-for-president/",
        "donate-w?source_code=next-step"
      ),
      "https://secure.anedot.com/walsh-for-president/donate-email",
      "https://secure.anedot.com/walsh-for-president/iowa",
      "https://secure.anedot.com/walsh-for-president/sweatshirt"
    ),
    FEC_ID_cmte = "C00717033",
    FEC_ID_cand = "P00013276"
  ),
  tibble(
    first_name = "Mark",
    last_name = "Sanford",
    campaign_name = "Sanford 2020",
    campaign_website = "https://www.marksanford.com/",
    actblue_link = NA,
    other_link = "https://secure.anedot.com/sanford-for-president/donate",
    FEC_ID_cmte = "C00285254",
    FEC_ID_cand = "P00013649"
  )
) %>%
  bind_rows() %>%
  mutate(
    year = 2020,
    party = "Rep"
  )

# Setup the Democratic candidates' information =================================
cand_dem_2020 <- list(
  tibble(
    first_name = "Michael",
    last_name = "Bennet",
    campaign_name = "Bennet for America",
    campaign_website = "https://michaelbennet.com/",
    actblue_link = c(
      "bennetwebsite",
      "nhinvestment",
      "bfa-11-21-19fb",
      "bfa-impeachment",
      "twoweeksad",
      "bfa-feb",
      "bfa-carville",
      "benneteoq",
      "bfalaunchdonor"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00705186",
    FEC_ID_cand = "P00011833"
  ),
  tibble(
    first_name = "Joseph",
    last_name = "Biden",
    campaign_name = "Biden for President",
    campaign_website = "https://joebiden.com/",
    actblue_link = c(
      "bff-abcd",
      "biden2020_fr_web",
      "biden2020_web_lightbox",
      "ads_dd_fb_edaydeadline_oct2020",
      "ads_dd_fb_fundraisingday_oct2020",
      "ads_dd_polling-reality_oct2020",
      "ads_dd_fb_repetitive_oct2020",
      "ads_dd_fb_egworried_oct2020",
      "ads_dd_fb_change_oct2020",
      "ads_dd_fb_trumpquotes_oct2020",
      "ads_dd_fb_campaignupdate_oct2020",
      "ads_dd_fb_lwvotered_oct2020",
      "ads_dd_fb_upsidedown_oct2020",
      "ads_dd_fb_55madbuy_oct2020",
      "ads_dd_fb_closingargument_oct2020",
      "ads_dd_fb_sameday_oct2020",
      "ads_dd_fb_voprofund_oct2020",
      "ads_dd_fb_noregrets_oct2020",
      "ads_dd_fb_final_debate_oct2020",
      "ads_dd_fb_100m_oct2020",
      "ads_dd_fb_polls6_oct2020",
      "ads_dd_fb_moe_oct2020",
      "ads_dd_fb_scarypolls7_oct2020",
      "ads_dd_fb_outspent_google_oct2020",
      "ads_dd_fb_town_hall_oct2020",
      "ads_dd_fb_undecided_oct2020",
      "ads_dd_fb_no_pollercoaster_oct2020",
      "ads_dd_fb_outraisedcycle_oct2020",
      "ads_dd_gs_general", # Victory Fund
      "joe2020",
      "biden2020_frq3_embed",
      "biden2020_search_embed_a",
      "biden2020_fr_q32020_sms",
      "biden2020_fr_q32020_sms_bhovideo",
      "joebiden1",
      "biden_gsdd_a",
      "biden2020_fb_acq_ads",
      "biden2020_ads",
      "joe2020_ads",
      "biden2020-dinner-contest-a",
      "biden2020_fr_beattrumpfund_a",
      "biden2020_bfpads",
      "biden2020_q3_ads",
      "biden2020_fr_q42019_rapidresponse_a",
      "biden_2020_july2019_a",
      "dd_ads_akdjflkaj",
      "julydebatecontest-a",
      "biden2020_fr_june2019_a",
      "biden2020_fr_stickers_a",
      "biden2020_fr_junedebatecontest",
      "biden2020_fr_q12020",
      "biden2020_fr_q12020-social1",
      "biden2020_fr_q12020-social2",
      "biden2020_fr_q12020-social3",
      "biden2020_fr_q12020-social4",
      "biden2020_fr_q12020-social5",
      "biden2020_fr_q12020-social6",
      "biden2020_fr_q12020-social7",
      "biden2020_fr_q12020-social8",
      "biden2020_fr_q12020-social9",
      "biden2020_fr_q12020-social10",
      "biden2020_fr_q12020-social11",
      "biden2020_fr_q12020-iowa2weeks",
      "biden2020_fr_q12020-social2",
      "biden2020_sfc_q12020",
      "biden2020_fr_malarkeycard",
      "biden2020_fr_q12020_hd",
      "biden2020_fr_stickers",
      "biden2020_wantjoesticker",
      "biden-fundraising-dashboard",
      "biden2020_fr_q22019",
      "biden2020_fr_q32019",
      "biden2020_fr_q32019_eoq",
      "biden2020_fr_q42019",
      "biden2020_fr_q42019-social",
      "biden2020_fr_q42019-social2",
      "biden2020_fr_q42019-social3",
      "biden2020_fr_q42019-social4",
      "biden2020_fr_q42019-social5",
      "biden2020_fr_q42019-social6",
      "biden2020_fr_q42019-social7",
      "biden2020_fr_q42019-social8",
      "biden2020_fr_q42019-social9",
      "biden2020_fr_q42019-social10",
      "biden2020_fr_q42019-social11",
      "biden2020_fr_q42019_openletter",
      "biden2020_fr_q42019_rapidresponse",
      "biden2020_fr_q42019_beattrumpfund",
      "biden2020_fr_q42019_match",
      "octoberdebatecontest",
      "biden2020_fr_footer",
      "bidendems",
      "bvf_gs_ads_dd",
      "biden2020_fr_autoresponder"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00703975",
    FEC_ID_cand = "P80000722"
  ),
  tibble(
    first_name = "Mike",
    last_name = "Bloomberg",
    campaign_name = "Mike Bloomberg 2020",
    campaign_website = "https://www.mikebloomberg.com",
    actblue_link = "",
    other_link = NA,
    FEC_ID_cmte = "C00728154",
    FEC_ID_cand = "P00009910"
  ),
  tibble(
    first_name = "Cory",
    last_name = "Booker",
    campaign_name = "Cory 2020",
    campaign_website = "https://corybooker.com/",
    actblue_link = c(
      "cory2020",
      "cory2020-rd/?source=&refcode=&action_code=FgxRWxYUOVIKQV0YAlIGTFM&td=TZDLasMwEEV_xWgdGUkmje1VS6F0H7oqRciS4ojqhR6FpPTfO3ZMU200c-do7oy-kQzVl3RBI3o7oh3SThgLSc6fxrXyZLzwUj_Oi9zK4AC5mgjAQCl5gMyFyVgNAsRJK5O0LLwme1P4XI3aQj4Ja0PZshAL_1pqvlq7QznUJLc2uU7_03gOXv9xJYALP4FnRuP7Byhm9jXyU0iOr17dYQ-vZNKiaK4WP0bogMmAWdeQfmR0pIc7YSIXSiXAaEdbRvct6-Dq70TNOnExa7_0enLiGnzzbENVLymABtxZxALMYk93aLIVjIXJFygYf5uKKkl6uSdYKTVhSvWAe8UEJv8OtFrW8MLpdWpGGty8BqcjuDfHddG8_rmqVm_YbX_08ws",
      "cory2020-gs",
      "cory2020-website",
      "cory2020-eoqsocial",
      "cory2020-debate-nov-lmdd-om",
      "om-cory2020-january",
      "cory2020-q4-om",
      "cory2020-countdown-iowa",
      "cory2020-q4-dd-om",
      "cory2020-eoy-om",
      "cory2020-debate-nov-om",
      "cory2020-underdog",
      "cory2020-rd",
      "cory2020-em-q3eoq",
      "cory2020-em-december",
      "cory2020-em-october",
      "cory2020-contest-cory-and-rosario",
      "em-cory2020-claimyoursticker",
      "cory2020-em-togetherad",
      "cory2020-em-bus-donor-wall",
      "cory2020-em-decdebate",
      "cory2020-em-decdebate-adsfund",
      "cory2020-em-dinnerwcab"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00695510",
    FEC_ID_cand = "P00009795"
  ),
  tibble(
    first_name = "Steve",
    last_name = "Bullock",
    campaign_name = "Bullock for President",
    campaign_website = "https://stevebullock.com/",
    actblue_link = c(
      "bfp2020_homepage",
      "bfp2020_homepage?refcode=SB_WEB_PET_2019.07.30_X_website_X__X__popup&amount=5&amounts=15,25,50,100,250,500&action_code=FgxRWxYUOVIKQV0YAFYKTFM&td=TVHbSgMxEP2Vkufukuz2srtPWqn4KFRREAnJJt0GcyPZKK347062xRoCmTlz5swZ8o16l-wYjqhDzzs0R9IwpSGJ8UOZst8ry2wvb4YMl70zQDkpD4SWELyCzDiutAQA4iCFCrIfaQr6jNAhKXEJKWdau_GSOT_Sz1yzSes5ii6FPsvsNvRlu6GP2ydaYdKWeF3WmL7SL8mjGiVE-XrnkweZmPhfJ6T-4Kz8kxwdGKJ7sBdR9_YOiBps8nTvgqGTLVK30NUHyUBZZGt5ZoHboqpnuOmqusPkylCeMiHC1EjKiizLqoanuTJSlIGyQdqsdWvYydnZnXZJ3AcHGPAOzI_AyePJHHGdYDBT8QgFZc-ulny1WLe8KYQQvCBEtkWzaKsC_zsgldewzOTVH5yRHsbOdtOG07eIpOWlfN4b_fwC"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00706416",
    FEC_ID_cand = "P00011999"
  ),
  tibble(
    first_name = "Pete",
    last_name = "Buttigieg",
    campaign_name = "Pete for America",
    campaign_website = "https://peteforamerica.com/",
    actblue_link = c(
      "pete-buttigieg-announcement-day",
      "pete-for-america",
      "pete-for-america-web-thanks?refcode=website_hero",
      "pete-buttigieg-access",
      "pete-buttigeig-email-marathon",
      "pete-buttigieg-emai-nh-bus",
      "pete-buttigeig-email-fishbowl",
      "pete-buttigieg-email-tv-ad",
      "pete-buttigieg-liberty-justice",
      "pete-buttigieg-email-iowa-100-days",
      "pete-buttigieg-womens-policy",
      "pete-buttigieg-email-iowa-ad-3",
      "pete-buttigieg-email-chasten-hamilton",
      "pete-buttigieg-email-ohio-debate-video",
      "pete-buttigieg-email-ohio-debate",
      "pete-buttigieg-welcome-email",
      "pete-buttigieg-liberty-justice",
      "embed-ads-direct_donate",
      "pete-buttigieg-social-contest-mjf",
      "pete-buttigieg-gft",
      "pete-buttigieg-email",
      "pete-buttigieg-today",
      "pete-buttigieg-today-evg-2020",
      "pete-buttigieg-today-pizza-2020",
      "pete-buttigieg-today-feb-sticker",
      "petebuttigieg",
      "pete-for-america-web-p5",
      "pete-for-america-web-p10",
      "pete-for-america-web-p20-20",
      "pete-for-america-web-p50",
      "pete-for-america-web-p100",
      "pete-for-america-web-p250",
      "pete-buttigieg?refcode=signup",
      "pete-buttigieg-social",
      "pete-buttigieg-eoq2",
      "pete-buttigieg-eoq3",
      "grassrootsfundraisingteam",
      "grassrootsinvestmentteam-2020"
    ),
    other_link = paste0(
      "https://secure.peteforamerica.com/onlineactions/",
      "02NYofXAckacUHa5Tf1xAw2?attr=101974418"
    ),
    FEC_ID_cmte = "C00697441",
    FEC_ID_cand = "P00010298"
  ),
  tibble(
    first_name = "Julian",
    last_name = "Castro",
    campaign_name = "Julian for the Future",
    campaign_website = "https://www.julianforthefuture.com/",
    actblue_link = c(
      "julianforthefuture",
      "julian-debates-ads",
      "julian-em",
      "debate-promotion-detroit-free",
      "castrocashbash-teamnh",
      "oct800",
      "julian-castro-2020-primary",
      "julian-castro-100kstickerchallenge",
      "julian-castro-2020",
      "em-diversity",
      "oct800",
      "julian-castro-em",
      "jcgen",
      "julian-castro-2020-pc"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00693044",
    FEC_ID_cand = "P00010298"
  ),
  tibble(
    first_name = "Bill",
    last_name = "de Blasio",
    campaign_name = "De Blasio 2020",
    campaign_website = "https://billdeblasio.com/",
    actblue_link = c(
      "de_blasio_donate_is",
      "de_blasio_donate_now"
    ),
    FEC_ID_cmte = "C00706697",
    FEC_ID_cand = "P00012054"
  ),
  tibble(
    first_name = "John",
    last_name = "Delaney",
    campaign_name = "Delaney for President 2020",
    campaign_website = "https://www.johndelaney.com/",
    actblue_link = c(
      "john-delaney-2",
      "john-delaney-2?refcode=website_header?refcode=website_signup&action_code=FgxRWxYUOVIKQV0YA0gD&td=VZBdS8MwFIb_Sum1KU26ydqribg7QRzihUhIk7MumI-SD2ET_7una3EaAjnvOU_y5pyvUvrsUjiVXfmyL29KsEIbFDF-aFvJg3bCSdgOU7qS3iJy1iMCLaX1Larx6B2gxrCHmIj0LgmZSNJ2SQdQOoBMPAczZ_iQtZrDmHurE-mTW0q8F8b4tCg_Jv45sS4bg7TPQcLvzX8yeTTiB20glt3bO2b04PLIDz5YfrFjiMkAIgFXkwGraUvqlrCmqDcdw726EnrkQqmAGG1oxei6Yg0emyuRIwQuBnDTW3dWnL0r7o3PahdwBhN3FGNCZjKnOB6T0VjoeMKCdvOfqFytm54xopSShFJoidjINan_LHxqasKJy0SfHp4fu-IV-qgTFPtLk8UO64hZr7KBBZz7L79_AA",
      "jkd_fr_q12019",
      "jkd_worldseries",
      "jkd_aapis-for-delaney",
      "jkd_fr_q42019"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00508416",
    FEC_ID_cand = "P00006213"
  ),
  tibble(
    first_name = "Tulsi",
    last_name = "Gabbard",
    campaign_name = "Tulsi 2020",
    campaign_website = "https://www.tulsi2020.com/",
    actblue_link = c(
      "tulsi2020",
      "tulsi2020?refcode=web-signup-page",
      "tulsi-why",
      "tulsi-up-for-the-fight",
      "tulsi-womans-day",
      "tulsi-now",
      "tulsi-history",
      "tulsi-super-tuesday",
      "tulsi-cnn-elitism",
      "tulsi-people-powered",
      "tulsi-feb2020",
      "tulsi-4-days-left",
      "tulsi-feedback-thankyou",
      "tulsi-sms",
      "tulsi-country",
      "tulsi-country-ty",
      "itulsi-ask",
      "tulsi-favorite-job",
      "tulsi-sign-up",
      "we-the-people",
      "we-the-people-ty",
      "tulsi-proud",
      "tulsi-some-numbers",
      "tulsi-voices-heard",
      "tulsi-what-it-takes",
      "tulsi-105k",
      "tulsi-last-night",
      "tulsi-snow-tickets",
      "tulsijrendorsed1",
      "tulsi-detroit",
      "love-war",
      "tulsi-cnn",
      "tulsi-hrc-legal-fund",
      "tulsi_mj_video",
      "tulsi_environment_video",
      "tulsi_healthcare_video",
      "tulsi_immigration_video",
      "tulsi_college4all",
      "tulsi_2nd_debate_1",
      "tulsi_2nd_debate_2",
      "tulsi-eoq-deadline",
      "fbt_debate_sk",
      "tulsi2020-donate",
      "tulsi-4-days",
      "tulsi-december-deadline",
      "tulsi-debates-aug",
      "tulsi-india",
      "tulsi_sk",
      "tulsi-donate-cta",
      "tulsi-clintons-colors",
      "tulsi-voice",
      "tulsi-dnc-ty",
      "tulsi-boyc-ask",
      "fbt_debate_sk",
      "tulsi-debates-aug",
      "tulsi-debates2",
      "tulsi-peace",
      "tulsi-debates",
      "65k-february",
      "65k-feb",
      "tulsi-oct-eom"
    ),
    other_link = "https://actions.ngpvan.com/v1/Forms/Z6oLz5EpVUm--I3N07pFlw2",
    FEC_ID_cmte = "C00693713",
    FEC_ID_cand = "P00009183"
  ),
  tibble(
    first_name = "Kirsten",
    last_name = "Gillibrand",
    campaign_name = "Gillibrand 2020",
    campaign_website = "https://kirstengillibrand.com/",
    actblue_link = c(
      "kg-website-2020", 
      "kg-social"
    ),
    FEC_ID_cmte = "C00694018",
    FEC_ID_cand = "P00009290"
  ),
  tibble(
    first_name = "Mike",
    last_name = "Gravel",
    campaign_name = "Gravel 2020",
    campaign_website = "https://www.mikegravel.org/",
    actblue_link = "mikegravel2020",
    FEC_ID_cmte = "",
    FEC_ID_cand = ""
  ),
  tibble(
    first_name = "Kamala",
    last_name = "Harris",
    campaign_name = "Kamala Harris For the People",
    campaign_website = "https://kamalaharris.org/",
    actblue_link = c(
      "kdh-q4-website",
      "kdh-q1-website",
      paste0(
        "kdh-q4-website?action_id=53165290&akid=.8032869.5huBwm&ar=1&",
        "rd=1&source=signup_frontpage"
      ),
      "kamala-harris-2020",
      "kdh-1901-eom",
      "kdh-ads-191121-debate-dd-fb",
      "kdh-ads-191120-new-ad-dd-fb",
      "kdh-ads-190920-new-ad-dd-fb",
      "kdh-ads-1901030-iowa-dd-fb",
      "kdh-ads-1901026-trumpattack-dd-fb",
      "kdh-ads-191015-postdebate-dd-fb",
      "kdh-ads-191011-midmonth-dd-fb",
      "kdh-ads-190930-eoq-dd-fb-2",
      "kdh-ads-190930-eoq-dd-ig-2",
      "kdh-ads-190930-eoq-dd-ig",
      "kdh-ads-190930-eoq-dd-fb",
      "kdh-ads-190929-eoq-dd-fb-2",
      "kdh-ads-190929-eoq-dd-fb",
      "kdh-ads-190928-eoq-dd-fb",
      "kdh-ads-190927-eoq-dd-fb-3",
      "kdh-ads-190926-eoq-dd-fb",
      "kdh-ads-190927-eoq-dd-fb-2",
      "kdh-ads-190927-eoq-dd-fb",
      "kdh-ads-190925-eoq-dd-fb-2",
      "kdh-ads-190925-eoq-dd-fb",
      "kdh-ads-190924-eoq-dd-fb",
      "kdh-ads-190923-eoq-dd-fb",
      "kdh-ads-190922-eoq-dd-fb",
      "kdh-ads-190920-eoq-dd-fb",
      "kdh-ads-190914-midmonth-dd-fb",
      "kdh-ads-190912-postdebate-dd-fb",
      "kdh-ads-190912-middebate-dd-fb/",
      "kdh-190121-evergreen-search-dd-ads",
      "kdh-190128-evergreen-tw-ads",
      "kdh-190128-evergreen-search-ads",
      "kdh-team-1903-q1",
      "kdh-web-1906-q2-teamcompetition",
      "kdh-web-190626-lightbox",
      "kdh-1907-social",
      "kdh-190121-launch",
      "kdh-ema-190707-july-contest",
      "kdh-sms-190722-debate",
      "kdh-ema-190726-eom",
      "kdh-ads-190731-evergreen-search",
      "kdh-web-190731-lightbox",
      "kdh-ema-190820",
      "kdh-ema-190821-contest",
      "dh-sms-190904-sticker",
      "kdh-web-190911-lightbox",
      "kdh-web-190911-alert-bar",
      "kdh-social-1909",
      "kdh-web-1909-q3-teamcompetition",
      "kdh-ema-190923",
      "kdh-ema-190924",
      "kdh-ema-190924-contest",
      "kdh-ema-190925",
      "kdh-ema-190926",
      "kdh-ema-190927",
      "kdh-ema-190928",
      "kdh-ema-190929",
      "kdh-ema-190930",
      "kdh-ema-191001",
      "kdh-ema-191009-debate",
      "kdh-sms-191015-debate",
      "kdh-ema-191016",
      "kdh-ema-191029-eom",
      "kdh-sms-191030-eom-p2p",
      "kdh-ema-191030-eom",
      "kdh-social-191101-all-in",
      "kdh-social-1910",
      "kdh-grassroots-notcapnamerica",
      "kdh-web-191115-alert-bar?refcode=website-alertbar",
      "kdh-social-november-challenge",
      "kdh-social-1911",
      "kdh-grassroots-united4kamala",
      "kdh-ema-191201"
    ),
    other_link = c(
      "https://give.kamalaharris.org/onlineactions/4TuMnaE_P02IlLzm-zA3Wg2?attr=101039457",
      "https://give.kamalaharris.org/onlineactions/NWTCmU3zBkuvW5l0rB4LQg2?attr=100622879",
      rep("", 74)
    ),
    FEC_ID_cmte = "C00694455",
    FEC_ID_cand = "P00009423"
  ),
  tibble(
    first_name = "John",
    last_name = "Hickenlooper",
    campaign_name = "Hickenlooper 2020",
    campaign_website = "https://www.hickenlooper.com/",
    actblue_link = "jh-homepage",
    FEC_ID_cmte = "C00698258",
    FEC_ID_cand = "P00010520"
  ),
  tibble(
    first_name = "Jay",
    last_name = "Inslee",
    campaign_name = "Inslee Our Moment",
    campaign_website = "https://jayinslee.com/",
    actblue_link = c(
      "our-moment", 
      "inslee100k", 
      "inslee120k",
      "inslee65k"
    ),
    FEC_ID_cmte = "C00698050",
    FEC_ID_cand = "P00010454"
  ),
  tibble(
    first_name = "Amy",
    last_name = "Klobuchar",
    campaign_name = "Amy for America",
    campaign_website = "https://amyklobuchar.com/",
    actblue_link = c(
      "klobuchar2020",
      "afa_launch_website",
      "afa_launch_website?refcode=https%3A%2F%2Famyklobuchar.com%2F_popup&action_code=FgxRWxYUOVIKQV0YA0gD&td=TZDbTsMwDIZfpcr12iUdbGuvQKC9wIS4YChKk7SNlpNyQNoQ746zTQNfxb8_27_zjbjLNoUT6tHbHi2QNExpSGI8KtPwUVlmuXyaitxwZwA5Kw9ARwheQxakUEHyRHMofaDQKStxe9KBae3SLXM-0a9Ss1nrBYouBy6hNqfkY39YHpbMnI7aDZnPLJR1hyX0xTzcUe989qD52Vl5H5Qc2KCj0jKi_uMTFDXZ7OnogqEXMy308CBZklQUOy0mXY27ul1VeNuvNn3b_RHKUyZEAIzgbdOSTdM-PjTrf0SOMlA2SVtmPRt2drZ60S6LXXCgATczn4Apy8kCDTrDYqbiCQrKXj2tsRi42LS1gKgJkV09YIZr_C9gVDnCMlOuf5dDVElWr3JkWadqfzmz2gEBoHEia3lDrz-Afn4B",
      "afa-st1",
      "afa-strongtues",
      "dtd-supertuesgoal",
      "afa-vitalwork",
      "afa-momentumdm",
      "duforamy",
      "afa-winbig",
      "dtd-presupertues",
      "afa-scdebate",
      "afa-sccountdown",
      "dtd-prenvcaucus",
      "dtd-trumprally",
      "afa-prescdebate",
      "afa-strongest",
      "afa-postlvdebate",
      "afa-midlvdf",
      "afa-lvdf",
      "afa-jansurge2020",
      "afa-crunchtime",
      "afa-winnovember",
      "afa-whitehouse",
      "afa-primarycaucusseason",
      "afa-defeattrump",
      "afa-iaonemon",
      "afa-onemonthia",
      "afa-electionyear",
      "afa-eoy341k",
      "afa-keepsurging",
      "afa-newyear",
      "afa-fieldteam",
      "afa-decpostdebate",
      "afa-middecdebate",
      "afa-decdebate",
      "afa-150kdecdebate",
      "afa-determination",
      "afa-momentumsurging",
      "afa-keepgoing",
      "afa-2020ishere",
      "afa-demtowin",
      "afa-amywin",
      "afa-keepmomentum",
      "afa-jangoal",
      "afa-crunch-nd",
      "afa-onedayads",
      "afa-surge2020",
      "afa-newpoll",
      "afa-nominateamy",
      "afa-tothewhitehouse",
      "afa-1term",
      "afa-actnow",
      "afa-valentine",
      "afa-nominee",
      "dtd-nhincredible",
      "afa-crucial",
      "afa-1pri",
      "afa-thickofit",
      "afa-jan2020eom",
      "afa-caucustime",
      "afa-crunch",
      "afa-finishline",
      "afa-sendtrumppacking",
      "afa-strongprimary",
      "afa-earlystatesfund",
      "afa-moveforward",
      "afa-febpostdebate",
      "afa-febmiddeb",
      "afa-febpredebate",
      "afa-strong",
      "afa-allout",
      "afa-postjandebate",
      "afa-janpredebate",
      "afa-onedaygoal",
      "afa-donate",
      "afa-firstprimary",
      "dtd-postsotu",
      "dtd-nhprimary",
      "dtd-sotu",
      "dtd-precaucus",
      "dtd-janeomgoal",
      "dtd-250k",
      "afa-nyt",
      "dtd-wcbt",
      "dtd-moremoney",
      "dtd-earlystatefund",
      "dtd-activate2020",
      "dtd-activate2020",
      "dtd-balldrop",
      "dtd-snowglobe",
      "dtd-341k",
      "dtd-2020mc",
      "dtd_ml",
      "dtd-exboyfriend", # I... really?
      "dtd-giftofamy",
      "dtd-predecdebategoal",
      "dtd-tvrefresh",
      "afa-decdebatecontest",
      "dtd-thanksgivinghotdish",
      "dtd-noveom",
      "dtd-womanpresident",
      "dtd-novpostdebate",
      "dtd-novbumper",
      "afa-exes",
      "dtd-listofsuppevgr",
      "dtd-electability",
      "dtd_hotdish",
      "dtd-decreqs",
      "dtd-decreqsdeadline",
      "dtd-directmail",
      "dtd-performancenovdebate",
      "afa-octpostdebate",
      "dtd-plansbs",
      "dtd-plans",
      "dtd-listofsuppdeb",
      "dtd-novdebate",
      "dtd-octdebategoal",
      "dtd-tvad1001",
      "dtd_stickers",
      "dtd-eoq3goal",
      "dtd_microgoal",
      "dtd_dncgoal",
      "afa-houstondeadline",
      "dtd_odonnell",
      "dtd_yardsigns",
      "dtd_postjulydebate",
      "afa_nd_v1",
      "afa_nd_v2",
      "dtd_listofdonors",
      "dtd_debateslideshow",
      "dtd_worstnightmare",
      "afa_bs",
      "afa-debatecontest2",
      "dtd_postdebatevid",
      "dtd_postdebate",
      "dtd-postdebate",
      "dtd_supportergoal",
      "acq_supportergoal",
      "dtd_supportergoal3",
      "dtd_supportergoal2",
      "afa-debatecontest",
      "afa-abgif",
      "acq_supportergoal2",
      "dtd_fbs",
      "afa-polls",
      "afa_fdon_v1",
      "afa_fdon_v2",
      "afa_ndny_v1",
      "afa_ndny_v2",
      "afa_ndfl_v1",
      "afa_ndfl_v2",
      "afa_ndca_v1",
      "afa_ndca_v2",
      "afa_ndmn_v1",
      "afa_ndmn_v2",
      "afa_debate_loc",
      "afa-wdebates",
      "afa-octdebatecontest",
      "afa-debaterule",
      "afa_launch_v1_dtdgs",
      "afa-debatecontest",
      "afa_debates_v1",
      "afa_debates_v2",
      "afa_trumptweetdtd",
      "afa_launch_v1",
      "afa_launch_v2",
      "afa_launch_v3",
      "afa_dtd_031919",
      "afa_launch_recurring",
      "ads_fb_d2doct_dl",
      "ads_fb_d2d_august2018",
      "ads-d2d-fb-jul2018",
      "afa-augeom",
      "afa-10k",
      "amy-klobuchar-3",
      "afa-beattrump",
      "afa-eoq3",
      "afa-octeom"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00696419",
    FEC_ID_cand = "P80006117"
  ),
  tibble(
    first_name = "Wayne",
    last_name = "Messam",
    campaign_name = "Wayne for America",
    campaign_website = "https://wayneforusa.com/",
    actblue_link = "messam-exp",
    FEC_ID_cmte = "C00699280",
    FEC_ID_cand = "P00010827"
  ),
  tibble(
    first_name = "Seth",
    last_name = "Moulton",
    campaign_name = "Seth Moulton for America",
    campaign_website = "https://sethmoulton.com/",
    actblue_link = c(
      "Seth-Moulton-1",
      "Seth-Moulton-2",
      "sethmoulton2020website"
    ),
    FEC_ID_cmte = "C00704510",
    FEC_ID_cand = "P00011866"
  ),
  tibble(
  first_name = "Robert",
  last_name = "O'Rourke",
  campaign_name = "Beto for America",
  campaign_website = "https://betoorourke.com/",
  actblue_link = c(
    "beto-launch",
    "betoforamerica",
    "betoforamerica?action_id=25406495&akid=.3448187.0vnoIg&ar=1&rd=1&refcode=web-nav-header&source=web-nav-header",
    "beto-launch",
    "beto-launch-sticker",
    "ads-google", # !!
    "beto-for-america-emails",
    "beto-email-20190317",
    "beto-email-20190321",
    "beto-email-20190323",
    "beto-email-20190325",
    "beto-email-20190326",
    "beto-email-20190327",
    "beto-email-20190329",
    "beto-email-20190330",
    "beto-email-20190331",
    "beto-sms",
    "ads-google-acqredirect",
    "beto-email-20190402",
    "beto-email-20190403",
    "beto-email-20190406",
    "beto-email-20190407",
    "beto-email-20190408",
    "beto-email-20190411",
    "beto-email-20190413",
    "beto-email-20190413",
    "beto-email-20190416",
    "beto-email-20190418",
    "beto-email-20190421",
    "beto-email-20190423",
    "beto-email-20190425",
    "beto-email-20190426",
    "beto-email-20190429",
    "beto-email-20190430",
    "beto-email-20190502",
    "beto-email-20190504",
    "beto-email-20190506",
    "beto-email-20190508",
    "beto-email-20190513",
    "beto-email-20190514",
    "beto-email-20190515",
    "beto-email-20190520",
    "beto-email-20190521",
    "beto-email-20190522",
    "beto-email-20190525",
    "beto-email-20190530",
    "beto-email-20190531",
    "beto-email-20190606",
    "beto-email-20190608",
    "beto-email-20190610",
    "beto-email-20190611",
    "beto-email-20190612",
    "beto-email-20190612",
    "beto-email-20190614",
    "beto-email-20190616",
    "beto-email-20190617",
    "beto-email-20190618",
    "beto-email-20190619",
    "beto-email-20190620",
    "beto-email-20190623",
    "beto-email-20190624",
    "beto-email-20190625",
    "beto-email-20190628",
    "beto-email-20190707",
    "beto-email-20190709",
    "beto-email-20190712",
    "beto-email-20190716",
    "beto-email-20190720-1",
    "beto-email-20190721",
    "beto-email-20190725",
    "beto-email-20190726-am",
    "beto-email-20190727-am",
    "beto-email-20190728-am",
    "beto-email-20190729-am",
    "beto-email-20190730-am",
    "beto-email-20190731-pm",
    "beto-email-20190801",
    "beto-email-20190802-am",
    "beto-email-20190815-am",
    "beto-email-20190816-am",
    "beto-email-jdscholten-20190817",
    "beto-email-20190817",
    "beto-email-20190818",
    "beto-email-20190819",
    "beto-email-20190820-am",
    "beto-email-20190820-am",
    "beto-email-20190821-am",
    "beto-email-20190822-am",
    "beto-email-20190823-am",
    "beto-email-20190823-after",
    "beto-email-20190824-after",
    "beto-email-20190825-am",
    "beto-email-20190827-am",
    "beto-email-20190829-am",
    "beto-email-20190830-am",
    "beto-email-20190831-am",
    "endofaugusttwitter",
    "town-hall-for-america",
    "beto-email-20190902-am",
    "beto-email-20190903-am",
    "beto-email-20190906-am",
    "beto-email-20190908-am",
    "beto-email-20190909-am",
    "beto-email-20190910-am",
    "beto-email-20190911-am",
    "beto-email-20190912-am",
    "beto-email-20190913-am",
    "beto-email-20190914-am",
    "beto-email-20190915-am",
    "beto-email-20190916-am",
    "beto-email-20190918-am",
    "beto-email-20190919-am",
    "beto-email-20190920-am",
    "beto-email-20190921-am",
    "beto-email-20190921-after",
    "beto-email-20190922-am",
    "beto-email-20190922-after",
    "beto-email-20190923-after",
    "beto-email-20190924-am",
    "beto-email-20190925-am",
    "beto-email-20190926-birthday-am",
    "beto-email-20190928-am",
    "beto-email-20190929-1",
    "beto-email-20191003-am",
    "beto-email-20191007-pm",
    "beto-email-20191007-after",
    "beto-email-20191009-am",
    "beto-email-20191010-am",
    "beto-email-20191011-newsletter",
    "beto-email-20191013-am",
    "beto-email-20191014",
    "beto-email-20191015-am",
    "beto-email-20191016-am",
    "beto-email-20191017-am`",
    "beto-email-20191018-am",
    "beto-email-20191019-am-after",
    "beto-email-20191020-am",
    "beto-email-20191021-am",
    "beto-email-20191022-am",
    "beto-email-20191023-1",
    "beto-email-20191023-2",
    "beto-email-20191024-1",
    "beto-email-20191024-2",
    "beto-email-20191025-1",
    "beto-email-20191025-2",
    "beto-email-20191026-1",
    "beto-email-20191026-2",
    "beto-email-20191027-1",
    "beto-email-20191027-2",
    "beto-email-20191028-1",
    "beto-email-20191028-2",
    "beto-email-20191029-1",
    "beto-email-20191029-2",
    "beto-email-20191030-1",
    "beto-email-20191030-2",
    "beto-email-20191031-1",
    "beto-email-20191031-2",
    "how-we-win-organizing"
  ),
  other_link = NA,
  FEC_ID_cmte = "C00699090",
  FEC_ID_cand = "P00010793"
  ),
  tibble(
    first_name = "Timothy",
    last_name = "Ryan",
    campaign_name = "Tim Ryan for America",
    campaign_website = "https://timryanforamerica.com/",
    actblue_link = c(
      "tr-ctr-website",
      "pop-up-debate",
      "tta-tr-pres-website?refcode=Website_Signup&amount=25&recurring=auto&action_code=FgxRWxYUOVIKQV0YAFEBTFM&td=TVBLa8MwDP4rwec6xFnSNTl1DHYelLHDGMaOldTMsYMfg3bsv09uQzudrO-hz9IPGVyy0Z9IT94OZENgFtpgE8KXnsth1FbYAfZThsvBzSg56wUFHWPVFjsPSnsYIk8--xDhU9JqfXIpjHFx7dwS-XfmbDJmQ4JLfgDk3kEGHYEf9GTTgsqQ5I3Edjk6CzdXdJjJR20gkP7jE5GLjY_Oz_ySzJoaXYMHgUNVTq8r1tGqo_VDUe36purb5q7QCxdK-WysdmXNHsu6bcptd1ekAJ6LCWye9TSLs7PFs3FJvXiHGOqOYomoyfFsQ6RJGCx0OCGh7fVXSrajqmVDFRZlDDq6k62i1b_CUXkNK-a8-quHUNBiPU-Rz1Nc7jM7lQysquv65PcP",
      "tr-debate-0719",
      "tr-mindful-leadership-contest",
      "tr_fb_d2d_debate_062619",
      "tr_fb_d2d_msnbc_062019",
      "tr-debatestage-a",
      "tr_fb_eom_05302019",
      "tr_fb_d2dvid_04272019",
      "lets-change-our-food-system-rt",
      "change-our-food",
      "tr_fb_uniond2d_04262019",
      "support-mindfulness-in-schools",
      "65000donors",
      "mindfulness-in-schools",
      "tr-welcome"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00701979",
    FEC_ID_cand = "P00011338"
  ),
  tibble(
    first_name = "Deval",
    last_name = "Patrick",
    campaign_name = "Deval Patrick 2020",
    campaign_website = "https://devalpatrick2020.com",
    actblue_link = c(
      "dlp-site",
      "dlp-homepage-signup?action_code=FgxRWxYUOVIKQV0YBkgD&td=fVJLb9QwEP4rVi6AhLN2ss2W9MIJkHhcoOLAIsuxJ7tW_Yj8KG0R_51xE7WcsCJrZr5vZj7P5HejQvE53jdjc_21ed2Ak8aik9KNca2ajZdewdtTDbcqOKTMJqbspQOk1RQrn9yP6D6YBa03nLMBPRcmYyuE9gQpUxV8lirTbNwWjqBNBJVFiXaNiFMxejVTmZzJdMoe_U-QXySiA8lnkypPTNLakLessGRxWxN9sRZTQ4mq9jgHB4s8AU3m5CGmtez_4OUcPDzVyQElihnfkZrxx0-MILEsYg7RiUehB8xREWQGoauajnWMMk45I4yP_DCyy2eGWYTUOiKN79uhb_uuvXhGS4IoUI2vdT6HB2OtPO4uWkZefjdeh1-JfPlGOGvZFcHAsL8id_WKt-Oha9kr8h7UTTjuOsYZfpy8w-HO4e64q3Dtc5ZLxh5VOMel2IKipUn3CBi_vgcmeYBBdrTv9wPlHCS97DVQ9s-pfwIOYNv8h22IpM6GlOVx9bpY2PB1ZM2fvw",
      "dlpe200210pm",
      "dlpe200210am",
      "dlpe200209",
      "dlpe200208",
      "dlpe200207_2",
      "dlpe200207",
      "dlpe200206",
      "dlpe200205",
      "dlpe200204_2",
      "dlpe200204",
      "dlpe200131pm",
      "dlpe200131am",
      "dlpe200130",
      "dlpe200129",
      "dlpe200128",
      "dlpe200127",
      "dlpe200124",
      "dlpe200123",
      "dlpe200118pm",
      "dlpe200118am",
      "dlpe200117",
      "dlpe200116_2",
      "dlpe200115",
      "dlpw191114fbdd",
      "dlpe200114"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00727156",
    FEC_ID_cand = "P00014407"
  ),
  tibble(
    first_name = "Bernard",
    last_name = "Sanders",
    campaign_name = "Bernie 2020",
    campaign_website = "https://berniesanders.com/",
    actblue_link = c(
      "bern-site",
      "bernie-2020-splash",
      "bernie-aoc-split",
      "mi-contribute-button",
      "bernie-march-donate",
      "ads-fb-dtd-bernie-pre-super-tues",
      "mi-bernie-march-donate",
      "bernie-fight-the-power-poster",
      "bernieforprez2020",
      "bands4bernie",
      "bernie-february-fec-deadline",
      "bernie-feb-txt",
      "bernie-text-feb-fec-deadline",
      "mi-bernie-february-donate",
      "bernie-fight-for-me-sticker",
      "feb-bernie-fight-sticker",
      "ctuforbernie",
      "bern-app-donate",
      "bernie-february-split", # Split btw 12 entities
      "ads-fb-dtd-bernie-nevada",
      "ads-fb-dtd-attack-2",
      "ads-fb-inact-attack-2",
      "ads-fb-dtd-donate-nh-victory",
      "bernie-new-hampshire-primary",
      "bernie-february-donate",
      "ads-gs-20evergreensearch_dtd",
      "ads-fb-dtd-bernie-new-hampshire",
      "ads-fb-dtd-bernie-new-hampshire-2",
      "ads-fb-dtd-bernie-new-hampshire-inact",
      "ads-fb-dtd-bernie-deb-donate-iowa-victory",
      "ads-fb-dtd-bernie-iowa",
      "bernie-jan-eoq-text",
      "bernie-january-fec",
      "bernie-oct-eom",
      "bernie-january-donate-txt",
      "bernie-january-donate",
      "bernie-jan-splash",
      "bern_site?action_id=40067293&akid=.10104727.UywRYX&ar=1&rd=1&refcode=website-splash-blue-vid_other",
      "bernie-may-donate",
      "social-june-deadline",
      "bernie-june-donate",
      "bernie-july-donate",
      "bernie-august-donate",
      "ads-tw-dtd-bernie-sept-eoq",
      "bernie-september-eoq",
      "bernie-september-eoq-max",
      "bernie-damn-bill-sticker",
      "bernie-splash-sept",
      "bernie-baseball",
      "bernie-billionaires-sticker",
      "bernie-green-new-deal-sticker",
      "ads-tw-dtd-squad-endorse",
      "bernie-iowa-rallies",
      "bernie-i-will-fight-sticker-txt",
      "bernie-i-will-fight-sticker",
      "bernie-rising-up-video",
      "bernie-mi-october-debate",
      "bernie-october-debate",
      "bernie-october-splash",
      "bernie-october-donate",
      "bernie-october-eom",
      "ads-gs-everygreensearch3_dtd",
      "bernie-december-donate",
      "ads-tw-dtd-bernie-oct-eom",
      "bernie-november-donate"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00696948",
    FEC_ID_cand = "P60007168"
  ),
  tibble(
    first_name = "Joe",
    last_name = "Sestak",
    campaign_name = "Joe Sestak for President",
    campaign_website = "https://www.joesestak.com/",
    actblue_link = c(
      "sestak2020",
      "joenhwalkb",
      "sestaknhad",
      "joenhwalk45",
      "sestaknh",
      "sestak36nh"
    ),
    other_link = NA,
    FEC_ID_cmte = "P00012567",
    FEC_ID_cand = "C00710574"
  ),
  tibble(
    first_name = "Tom",
    last_name = "Steyer",
    campaign_name = "Tom 2020",
    campaign_website = "https://www.tomsteyer.com/",
    actblue_link = c(
      "2020ts",
      "ts2020?refcode=home&email=sskim.cfinance@gmail.com&zip=91106",
      "tom2020-on-the-trail-with-tom",
      "ts2020-tartan-tie-pin",
      "ts2020-sep-deadline",
      "tom2020-dec-debate", # Prompt for 9.94 at some point
      "tom2020-2button",
      "tom2020-jan-deadline",
      "tom2020-momentum",
      "ts2020-save-the-world-bumper-sticker",
      "tom2020-debate-stage",
      "tom2020-donation-fraud-failure-bumper-sticker",
      "tom2020-wealth-tax",
      "tom2020-term-limits",
      "tom2020-health-care",
      "tom2020-economy",
      "tom2020-climate-emergency",
      "tom2020-affordable-housing",
      "tom2020-reparations",
      "tom2020-immigration",
      "tom2020-hbcu",
      "tom2020-grassroots-supporters",
      "tom2020-donation-goal",
      "tom2020-impeached-sticker",
      "tom2020-make-them-testify-sticker",
      "tom2020-jan-debate",
      "tom2020-impeachment-button",
      "ts2020-imp-sticker",
      "tom2020-save-the-world-bumper-sticker",
      "tom2020-december-debate",
      "tom2020-climate-bumper-sticker",
      "tom2020-failure-fraud-sticker",
      "tom2020-impeach-sticker-orange",
      "tom2020-on-the-trail-with-tom",
      "tom2020-climate-crisis-button",
      "ts2020-5-button-pack",
      "tom2020-congress-do-your-job-button",
      "tom2020-fair-elections",
      "ts2020-imp-button",
      "ts2020-wealth-tax",
      "tom2020-dec-debate-bumper-sticker",
      "ts2020-hardball"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00711614",
    FEC_ID_cand = "P00012716"
  ),
  tibble(
    first_name = "Eric",
    last_name = "Swalwell",
    campaign_name = "Swalwell for America",
    campaign_website = "https://ericswalwell.com/",
    actblue_link = c(
      "ericswalwell",
      "getswalwelldebates",
      "swalwellq2",
      "passthetorch",
      "swalwellnato",
      "debatetrip",
      "letsendgunviolencenow"
    ),
    FEC_ID_cmte = "C00701698",
    FEC_ID_cand = "P00011312"
  ),
  tibble(
    first_name = "Elizabeth",
    last_name = "Warren",
    campaign_name = "Warren for President",
    campaign_website = "https://elizabethwarren.com/",
    actblue_link = c(
      "web-donate-bar",
      "ew-homepage-launch-050919",
      "grab-a-drink-with-ew",
      "augusttakeover-test",
      "august-notakeover-test",
      "web-q1-2020",
      "ew-om-dd",
      "ew-mar20fr-june2",
      "ew-om-dd-lmstk",
      "ew-om-dd-hd",
      "ew-febpin-om",
      "ew-splash-june2",
      "POTUS46",
      "chargrille",
      "pccc_warren",
      "soc-feb20team",
      "soc-febfr",
      "brettforwarren",
      "warren-for-president",
      "warrentinesday2020",
      "baileyblock",
      "sloaneleigh",
      "bootsy",
      "jl-and-elizabeth",
      "ew-jl-and-elizabeth-om",
      "ew-feb20fr-june2",
      "warren-pin4-june2",
      "ew-web-resp",
      "ew-goalsplash-june2",
      "web-hero-signup?refcodekey=null&refcodepath=%2F&refcodetemplate=pageCampaignHomepage&refcode=web-signup-hero", # signup
      "ew-eom-pin-om",
      "ew-nhsplash-march3",
      "ew-iowasplash-march3",
      "soc-7mil",
      "ew-events",
      "ew-ws",
      "jan20-takeover",
      "web-homepage-q4",
      "decdebate-takeover",
      "ew-june19social",
      "ew-oct19fr",
      "ew-web-q319",
      "ew-webtakeover-92419",
      "home-signup-redirect?refcode=web-signup&express_lane=true",
      "ew-homepage-ai",
      "ew-nh-debate-om",
      "soc-oct19fr",
      "soc-oct19debate",
      "ew-grab-a-beer-om",
      "ew-homepage-hero",
      "ew-webtakeover-92419",
      "ew-fight-back-donate",
      "ew-issuessurvey",
      "ew-q3-33",
      "ew-om-pet-thanks",
      "ew-grab-a-beer-om",
      "surrogate-calltime",
      "soc-oct19eom",
      "soc-eoqq32019",
      "soc-eoqcalltime",
      "soc-jan20fr",
      "tn-for-warren",
      "angry-and-i-own-it",
      "ew-2019q3eoq",
      "ew-2019q3eoq-sticker",
      "ew-psmm-sticker",
      "ew-homepage-launch-050919"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00693234",
    FEC_ID_cand = "P00009621"
  ),
  tibble(
    first_name = "Marianne",
    last_name = "Williamson",
    campaign_name = "Marianne 2020",
    campaign_website = "https://www.marianne2020.com/",
    actblue_link = c(
      "marianne-williamson-2020-committee",
      "marianne-williamson-1"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00696054",
    FEC_ID_cand = "P00009910"
  ),
  tibble(
    first_name = "Andrew",
    last_name = "Yang",
    campaign_name = "Yang 2020",
    campaign_website = "https://www.yang2020.com/",
    actblue_link = c(
      "friends-of-andrew-yang",
      "ayorganicdefault190527webegall",
      "ayorganicdefault190622webegall",
      "ayorganicdebatejune19190627genall",
      "ayorganicjulyeg19190701genall",
      "ay-organic-augeg19-190801--genall",
      "ay-web-homepage-20190819",
      "ay-web-october",
      "ay-web-november",
      "ay-web-december",
      "ay-web-january",
      "ay-web-february",
      "ay-email-mathhatgiveaway",
      "ay-email-vahouseofdelegates",
      "ay-email-halloweenpowerhour",
      "ay-ads-halloweenpowerhour",
      "ay-email-ohio-20191006",
      "andrews-ask",
      "46campaign-giveaway",
      "ay-ads-december",
      "ay-ads-november",
      "ay-ads-november-ad",
      "ay-ads-social-october",
      "ay-email-february",
      "ay-email-january",
      "ay-email-december",
      "ay-email-november",
      "ay-email-november-adgoal",
      "ay-email-october",
      "ay-email-september",
      "ay-social-february",
      "ay-social-january",
      "ay-social-december",
      "ay-social-november",
      "ay-social-october",
      "ay-social-september",
      "financecommitee",
      "yanggame",
      "ay-ads-january",
      "ay-ads-february",
      "ay-ads-december",
      "ay-ads-november",
      "ay-ads-november-ad",
      "ay-ads-social-october",
      "ay-ads-september-d2d",
      "ay-email-september-eoqd2d",
      "ay-facebook-20190831",
      "ay-ads-iowafr-20190821",
      "ay-social-1905017-35goal",
      "ay-events-chappelleshowcharleston",
      "ay-ads-chappelle-giveaway",
      "andrewyangfb",
      "ay-web-december-full",
      "ay-web-february?utm_source=website&utm_medium=organic&utm_term=all&refcode=ay-web-join-form-all",
      "freedomfriday",
      "ay-ads-googlesearch-d2d",
      "ay-web-actionkit-20190820",
      "happybirthdaytoevelynyang#",
      "friends-of-andrew-yang"
    ),
    other_link = NA,
    FEC_ID_cmte = "C00659938",
    FEC_ID_cand = "P00006486"
  )
) %>%
  bind_rows() %>%
  mutate(
    year = 2020,
    party = "Dem",
    other_link = NA
  ) %>%
  rowwise() %>%
  mutate(
    actblue_link = paste0("https://secure.actblue.com/donate/", actblue_link),
    actblue_link = ifelse(
      actblue_link == "https://secure.actblue.com/donate/NA", NA, actblue_link
    )
  ) %>%
  ungroup()

# Combine into single dataframe ================================================
cand_pres_2020 <- bind_rows(cand_rep_2020, cand_dem_2020) %>%
  rowwise() %>%
  mutate(
    campaign_website = tolower(gsub("http://", "https://", campaign_website)),
    campaign_website = ifelse(
      grepl("www", campaign_website), campaign_website,
      gsub("://", "://www.", campaign_website)
    ),
    campaign_website = gsub("/$", "", campaign_website)
  ) %>%
  ungroup()
rm(cand_rep_2020, cand_dem_2020)
